routes/web.php
<?php

Auth::routes(['verify' => true]);


Route::get('/home', function () {
    return redirect('/admin/home');
});

Route::get('/', function () {
    return redirect('/admin/home');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
Route::post('register', 'Auth\RegisterController@register')->name('auth.register');

Route::group(['middleware' => ['auth', 'verified'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');

    Route::resource('ledgers', 'Admin\LedgersController');

    Route::resource('deposits', 'Admin\DepositsController');
    Route::resource('withdrawals', 'Admin\WithdrawalsController');
    Route::resource('transfers', 'Admin\TransfersController');
    Route::resource('statements', 'Admin\StatementsController');

    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy',
        ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);


});

resources/views/partials/head.blade.php
<meta charset="utf-8">
<title>
    {{ trans('global.global_title') }}
</title>
<meta name="google" content="notranslate">

<meta http-equiv="X-UA-Compatible"
      content="IE=edge">
<meta content="width=device-width, initial-scale=1.0"
      name="viewport"/>
<meta http-equiv="Content-type"
      content="text/html; charset=utf-8">

<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Ionicons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<link href="{{ url('adminlte/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
<link rel="stylesheet"
      href="{{ url('adminlte/css') }}/select2.min.css"/>
<link href="{{ url('adminlte/css/AdminLTE.min.css') }}" rel="stylesheet">
<link href="{{ url('adminlte/css/skins/skin-black-light.min.css') }}" rel="stylesheet">
<link rel="stylesheet"
      href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
<link rel="stylesheet"
      href="//cdn.datatables.net/1.10.9/css/jquery.dataTables.min.css"/>
<link rel="stylesheet"
      href="https://cdn.datatables.net/select/1.2.0/css/select.dataTables.min.css"/>
<link rel="stylesheet"
      href="//cdn.datatables.net/buttons/1.2.4/css/buttons.dataTables.min.css"/>

<link href="{{ url('adminlte/plugins/datetimepicker/bootstrap-datetimepicker.min.css') }}" rel="stylesheet"/>
<link href="{{ url('adminlte/css/custom.css') }}" rel="stylesheet">

resources/views/partials/header.blade.php
<div class="page-header-inner">
    <div class="page-header-inner">
        <div class="navbar-header">
            <a href="{{ url('/admin/home') }}"
               class="navbar-brand">
                @trans('global.global_title')
            </a>
        </div>
        <a href="javascript:;"
           class="menu-toggler responsive-toggler"
           data-toggle="collapse"
           data-target=".navbar-collapse">
        </a>

        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">

            </ul>
        </div>
    </div>
</div>

resources/views/partials/javascripts.blade.php
<script>
    window.deleteButtonTrans = '{{ trans("global.app_delete_selected") }}';
    window.copyButtonTrans = '{{ trans("global.app_copy") }}';
    window.csvButtonTrans = '{{ trans("global.app_csv") }}';
    window.excelButtonTrans = '{{ trans("global.app_excel") }}';
    window.pdfButtonTrans = '{{ trans("global.app_pdf") }}';
    window.printButtonTrans = '{{ trans("global.app_print") }}';
    window.colvisButtonTrans = '{{ trans("global.app_colvis") }}';
</script>
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="//cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.4/js/dataTables.buttons.min.js"></script>
<script src="//cdn.datatables.net/buttons/1.2.4/js/buttons.flash.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.print.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.4/js/buttons.colVis.min.js"></script>
<script src="https://cdn.datatables.net/select/1.2.0/js/dataTables.select.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
<script src="{{ url('adminlte/js') }}/bootstrap.min.js"></script>
<script src="{{ url('adminlte/js') }}/select2.full.min.js"></script>
<script src="{{ url('adminlte/js') }}/main.js"></script>

<script src="{{ url('adminlte/plugins/slimScroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ url('adminlte/plugins/fastclick/fastclick.js') }}"></script>
<script src="{{ url('adminlte/js/app.min.js') }}"></script>
<script>
    window._token = '{{ csrf_token() }}';
</script>
<script>
    $.extend(true, $.fn.dataTable.defaults, {
        "language": {
            "url": "https://cdn.datatables.net/plug-ins/1.10.16/i18n/English.json"
        }
    });


</script>

<script>
    $(function () {
        /** add active class and stay opened when selected */
        var url = window.location;

        // for sidebar menu entirely but not cover treeview
        $('ul.sidebar-menu a').filter(function () {
            return this.href == url;
        }).parent().addClass('active');

        $('ul.treeview-menu a').filter(function () {
            return this.href == url;
        }).parent().addClass('active');

        // for treeview
        $('ul.treeview-menu a').filter(function () {
            return this.href == url;
        }).parentsUntil('.sidebar-menu > .treeview-menu').addClass('menu-open').css('display', 'block');
    });
</script>


@yield('javascript')

resources/views/partials/sidebar.blade.php
@inject('request', 'Illuminate\Http\Request')
<!-- Left side column. contains the sidebar -->

<aside class="main-sidebar hidden-lg">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <div class="user-panel" style="padding-top: 20px;padding-bottom: 20px">
            <div class="pull-left image">
                        <span class="text-circle-small" style="width: 60px; height: 60px;margin-right: 5px">
                            {{Auth::user()->userNameInitials ? Auth::user()->userNameInitials : ''}}
                        </span>
            </div>
            <div class="pull-left info" style="padding-left: 5px">
                <p>{{Auth::User()->name}}</p>
            </div>
        </div>

        <ul class="sidebar-menu">

            <li class="{{ $request->segment(1) == 'home' ? 'active' : '' }}">
                <a href="{{ url('/') }}">
                    <i class="fa fa-home"></i>
                    <span class="title">@lang('global.app_dashboard')</span>
                </a>
            </li>


            @can('deposit_create')
                <li>
                    <a href="{{ route('admin.deposits.create') }}">
                        <i class="fa fa-cloud-upload"></i>
                        <span>@lang('global.deposit.title')</span>
                    </a>
                </li>@endcan


            @can('withdraw_create')
                <li>
                    <a href="{{ route('admin.withdrawals.create') }}">
                        <i class="fa fa-cloud-download"></i>
                        <span>@lang('global.withdraw.title')</span>
                    </a>
                </li>@endcan


            @can('transfer_create')
                <li>
                    <a href="{{ route('admin.transfers.create') }}">
                        <i class="fa fa-exchange"></i>
                        <span>@lang('global.transfer.title')</span>
                    </a>
                </li>@endcan

            @can('statement_access')
                <li>
                    <a href="{{ route('admin.statements.index') }}">
                        <i class="fa fa-list"></i>
                        <span>@lang('global.statement.title')</span>
                    </a>
                </li>@endcan

            @can('ledger_access')
                <li>
                    <a href="{{ route('admin.ledgers.index') }}">
                        <i class="fa fa-dollar"></i>
                        <span>@lang('global.ledger.title')</span>
                    </a>
                </li>@endcan

            @can('user_management_access')
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-users"></i>
                        <span>@lang('global.user-management.title')</span>
                        <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                    </a>
                    <ul class="treeview-menu">
                        @can('permission_access')
                            <li>
                                <a href="{{ route('admin.permissions.index') }}">
                                    <i class="fa fa-briefcase"></i>
                                    <span>@lang('global.permissions.title')</span>
                                </a>
                            </li>@endcan

                        @can('role_access')
                            <li>
                                <a href="{{ route('admin.roles.index') }}">
                                    <i class="fa fa-briefcase"></i>
                                    <span>@lang('global.roles.title')</span>
                                </a>
                            </li>@endcan

                        @can('user_access')
                            <li>
                                <a href="{{ route('admin.users.index') }}">
                                    <i class="fa fa-user"></i>
                                    <span>@lang('global.users.title')</span>
                                </a>
                            </li>@endcan

                    </ul>
                </li>@endcan


            <li class="{{ $request->segment(1) == 'change_password' ? 'active' : '' }}">
                <a href="{{ route('auth.change_password') }}">
                    <i class="fa fa-key"></i>
                    <span class="title">@lang('global.app_change_password')</span>
                </a>
            </li>

            <li>
                <a href="#logout" onclick="$('#logout').submit();">
                    <i class="fa fa-arrow-left"></i>
                    <span class="title">@lang('global.app_logout')</span>
                </a>
            </li>
        </ul>
    </section>
</aside>

resources/views/partials/topbar.blade.php
@inject('request', 'Illuminate\Http\Request')

<header class="main-header  header-border-bottom">
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">

        <div class="row hidden-lg">
            <div class=" col-xs-1 ">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </div>
            <div class="col-xs-11">
                <div class="container-fluid ">
                        <ul class="nav navbar-nav ">
                            <li><a href="{{ url('/admin/home') }}"
                                   style="padding: 5px;">
                                    <div>
                                        <img src="{{ url('').'/company_logo.png'}}"
                                              style=" height: 41px">
                                    </div>
                                </a>
                            </li>
                        </ul>
                </div>
            </div>
        </div>


        <div class="row hidden-xs hidden-sm hidden-md">
            <div class="col-xs-3">
                <div class="collapse navbar-collapse pull-right" id="navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url('/admin/home') }}"
                               style="padding: 5px;">
                                <div style="text-align: left;">
                                    <img src="{{ url('').'/company_logo.png'}}"
                                          style=" height: 41px">
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-6">
                <div class="container-fluid">
                    <div class="collapse navbar-collapse" id="navbar-collapse">
                        <ul class="nav navbar-nav">

                            <li class="{{ $request->segment(2) == 'home' ? 'active' : '' }}">
                                <a href="{{ url('/') }}">
                                    <i class="fa fa-home"></i>
                                    <span class="title">@lang('global.app_dashboard')</span>
                                </a>
                            </li>


                            @can('deposit_create')
                                <li class="{{ $request->segment(2) == 'deposits' ? 'active' : '' }}">
                                    <a href="{{ route('admin.deposits.create') }}">
                                        <i class="fa fa-cloud-upload"></i>
                                        <span>@lang('global.deposit.title')</span>
                                    </a>
                                </li>@endcan


                            @can('withdraw_create')
                                <li class="{{ $request->segment(2) == 'withdrawals' ? 'active' : '' }}">
                                    <a href="{{ route('admin.withdrawals.create') }}">
                                        <i class="fa fa-cloud-download"></i>
                                        <span>@lang('global.withdraw.title')</span>
                                    </a>
                                </li>@endcan


                            @can('transfer_create')
                                <li class="{{ $request->segment(2) == 'transfers' ? 'active' : '' }}">
                                    <a href="{{ route('admin.transfers.create') }}">
                                        <i class="fa fa-exchange"></i>
                                        <span>@lang('global.transfer.title')</span>
                                    </a>
                                </li>@endcan

                            @can('statement_access')
                                <li class="{{ $request->segment(2) == 'statements' ? 'active' : '' }}">
                                    <a href="{{ route('admin.statements.index') }}">
                                        <i class="fa fa-list"></i>
                                        <span>@lang('global.statement.title')</span>
                                    </a>
                                </li>@endcan

                            @can('ledger_access')
                                <li class="{{ $request->segment(2) == 'ledgers' ? 'active' : '' }}">
                                    <a href="{{ route('admin.ledgers.index') }}">
                                        <i class="fa fa-dollar"></i>
                                        <span>@lang('global.ledger.title')</span>
                                    </a>
                                </li>@endcan


                            @can('user_management_access')
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle"
                                       data-toggle="dropdown">@lang('global.user-management.title') <span
                                                class="caret"></span></a>
                                    <ul class="dropdown-menu" role="menu">

                                        @can('permission_access')
                                            <li class="{{ $request->segment(2) == 'permissions' ? 'active' : '' }}">
                                                <a href="{{ route('admin.permissions.index') }}">
                                                    <i class="fa fa-briefcase"></i>
                                                    <span>@lang('global.permissions.title')</span>
                                                </a>
                                            </li>@endcan

                                        @can('role_access')
                                            <li class="{{ $request->segment(2) == 'roles' ? 'active' : '' }}">
                                                <a href="{{ route('admin.roles.index') }}">
                                                    <i class="fa fa-briefcase"></i>
                                                    <span>@lang('global.roles.title')</span>
                                                </a>
                                            </li>@endcan

                                        @can('user_access')
                                            <li class="{{ $request->segment(2) == 'users' ? 'active' : '' }}">
                                                <a href="{{ route('admin.users.index') }}">
                                                    <i class="fa fa-user"></i>
                                                    <span>@lang('global.users.title')</span>
                                                </a>
                                            </li>@endcan
                                    </ul>
                                </li>
                            @endcan
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xs-3">
                <div class="collapse navbar-collapse pull-right" id="navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="true">

                                <div class="text-center">

                                    <div class="table no-border no-margin">
                                        <tr>
                                            <td>
                                                <span class="text-circle-small" style="margin-right: 10px">
                                                    {{Auth::user()->userNameInitials ? Auth::user()->userNameInitials : ''}}
                                                </span>
                                            </td>
                                            <td class="text-primary-color"> {{Auth::User()->name}}<span
                                                        class="caret"></span>
                                            </td>
                                        </tr>
                                    </div>
                                </div>

                            </a>
                            <ul class="dropdown-menu dropdown-menu-right">

                                <li class="{{ $request->segment(1) == 'change_password' ? 'active' : '' }}">
                                    <a href="{{ route('auth.change_password') }}">
                                        <i class="fa fa-key"></i>
                                        <span class="title">@lang('global.app_change_password')</span>
                                    </a>
                                </li>
                                <li class="divider"></li>

                                <li>
                                    <a href="#logout" onclick="$('#logout').submit();">
                                        <i class="fa fa-arrow-left"></i>
                                        <span class="title">@lang('global.app_logout')</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </nav>
</header>