routes/web.php
<?php

Auth::routes(['verify' => true]);


Route::get('/home', function () {
    return redirect('/admin/home');
});

Route::get('/', function () {
    return redirect('/admin/home');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('auth.login');
Route::post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

// Registration Routes..
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('auth.register');
Route::post('register', 'Auth\RegisterController@register')->name('auth.register');

Route::group(['middleware' => ['auth', 'verified'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');

    Route::resource('ledgers', 'Admin\LedgersController');

    Route::resource('deposits', 'Admin\DepositsController');
    Route::resource('withdrawals', 'Admin\WithdrawalsController');
    Route::resource('transfers', 'Admin\TransfersController');
    Route::resource('statements', 'Admin\StatementsController');

    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy',
        ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);


});

app/User.php
<?php

namespace App;

use Hash;
use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
/**
 * Class User
 *
 * @package App
 * @property string $name
 * @property string $email
 * @property string $password
 * @property string $remember_token
 */
class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;
    protected $fillable = ['name', 'email', 'password', 'remember_token'];
    protected $hidden = ['password', 'remember_token'];


    /**
     * Hash password
     * @param $input
     */
    public function setPasswordAttribute($input)
    {
        if ($input) {
            $this->attributes['password'] = app('hash')->needsRehash($input) ? Hash::make($input) : $input;
        }
    }


    public function role()
    {
        return $this->belongsToMany(Role::class, 'role_user');
    }


    public function sendPasswordResetNotification($token)
    {
        $this->notify(new ResetPassword($token));
    }

    public function getUserNameInitialsAttribute()
    {

        $fullName = $this->name;

        $words = explode(" ", $fullName);
        $firstCharacter = $words[0][0];

        $lastCharacter = "";
        $counter = 0;
        foreach ($words as $w) {

            if ($counter == 0) {
                $counter++;
                continue;
            }
            $lastCharacter = $w[0][0];
        }

        $nameInitial = $firstCharacter . $lastCharacter;

        return $nameInitial;
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreUsersRequest;
use App\Http\Requests\Admin\UpdateUsersRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class UsersController extends Controller
{
    /**
     * Display a listing of User.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (!Gate::allows('user_access')) {
            return abort(401);
        }


        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating new User.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (!Gate::allows('user_create')) {
            return abort(401);
        }

        $roles = \App\Role::get()->pluck('title', 'id');


        return view('admin.users.create', compact('roles'));
    }

    /**
     * Store a newly created User in storage.
     *
     * @param  \App\Http\Requests\StoreUsersRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUsersRequest $request)
    {
        if (!Gate::allows('user_create')) {
            return abort(401);
        }
        $user = User::create($request->all());
        $user->role()->sync(array_filter((array)$request->input('role')));


        return redirect()->route('admin.users.index');
    }


    /**
     * Show the form for editing User.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!Gate::allows('user_edit')) {
            return abort(401);
        }

        $roles = \App\Role::get()->pluck('title', 'id');


        $user = User::findOrFail($id);

        return view('admin.users.edit', compact('user', 'roles'));
    }

    /**
     * Update User in storage.
     *
     * @param  \App\Http\Requests\UpdateUsersRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUsersRequest $request, $id)
    {
        if (!Gate::allows('user_edit')) {
            return abort(401);
        }
        $user = User::findOrFail($id);
        $user->update($request->all());
        $user->role()->sync(array_filter((array)$request->input('role')));


        return redirect()->route('admin.users.index');
    }


    /**
     * Display User.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!Gate::allows('user_view')) {
            return abort(401);
        }

        $roles = \App\Role::get()->pluck('title', 'id');
        $ledgers = \App\Ledger::where('created_by_id', $id)->get();

        $user = User::findOrFail($id);

        return view('admin.users.show', compact('user', 'ledgers'));
    }


    /**
     * Remove User from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!Gate::allows('user_delete')) {
            return abort(401);
        }
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('admin.users.index');
    }

    /**
     * Delete all selected User at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (!Gate::allows('user_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = User::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-6  col-md-offset-3">
            @include('include.messages')
            <h3 class="page-title">@lang('global.users.title')</h3>
            {!! Form::open(['method' => 'POST', 'route' => ['admin.users.store']]) !!}

            <div class="panel panel-default">
                <div class="panel-heading">
                    @lang('global.app_create')
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12 form-group">
                            {!! Form::label('name', trans('global.users.fields.name').'*', ['class' => 'control-label']) !!}
                            {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 form-group">
                            {!! Form::label('email', trans('global.users.fields.email').'*', ['class' => 'control-label']) !!}
                            {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('email'))
                                <p class="help-block">
                                    {{ $errors->first('email') }}
                                </p>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 form-group">
                            {!! Form::label('password', trans('global.users.fields.password').'*', ['class' => 'control-label']) !!}
                            {!! Form::password('password', ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('password'))
                                <p class="help-block">
                                    {{ $errors->first('password') }}
                                </p>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 form-group">
                            {!! Form::label('role', trans('global.users.fields.role').'*', ['class' => 'control-label']) !!}
                            <button type="button" class="btn btn-primary btn-xs" id="selectbtn-role">
                                {{ trans('global.app_select_all') }}
                            </button>
                            <button type="button" class="btn btn-primary btn-xs" id="deselectbtn-role">
                                {{ trans('global.app_deselect_all') }}
                            </button>
                            {!! Form::select('role[]', $roles, old('role'), ['class' => 'form-control select2', 'multiple' => 'multiple', 'id' => 'selectall-role' , 'required' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('role'))
                                <p class="help-block">
                                    {{ $errors->first('role') }}
                                </p>
                            @endif
                        </div>
                    </div>

                </div>
            </div>


            {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}

        </div>
    </div>

@stop

@section('javascript')
    @parent

    <script>
        $("#selectbtn-role").click(function () {
            $("#selectall-role > option").prop("selected", "selected");
            $("#selectall-role").trigger("change");
        });
        $("#deselectbtn-role").click(function () {
            $("#selectall-role > option").prop("selected", "");
            $("#selectall-role").trigger("change");
        });
    </script>
@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-md-6  col-md-offset-3">
            @include('include.messages')

            <h3 class="page-title">@lang('global.users.title')</h3>

            {!! Form::model($user, ['method' => 'PUT', 'route' => ['admin.users.update', $user->id]]) !!}

            <div class="panel panel-default">
                <div class="panel-heading">
                    @lang('global.app_edit')
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12 form-group">
                            {!! Form::label('name', trans('global.users.fields.name').'*', ['class' => 'control-label']) !!}
                            {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('name'))
                                <p class="help-block">
                                    {{ $errors->first('name') }}
                                </p>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 form-group">
                            {!! Form::label('email', trans('global.users.fields.email').'*', ['class' => 'control-label']) !!}
                            {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('email'))
                                <p class="help-block">
                                    {{ $errors->first('email') }}
                                </p>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 form-group">
                            {!! Form::label('password', trans('global.users.fields.password').'*', ['class' => 'control-label']) !!}
                            {!! Form::password('password', ['class' => 'form-control', 'placeholder' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('password'))
                                <p class="help-block">
                                    {{ $errors->first('password') }}
                                </p>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 form-group">
                            {!! Form::label('role', trans('global.users.fields.role').'*', ['class' => 'control-label']) !!}
                            <button type="button" class="btn btn-primary btn-xs" id="selectbtn-role">
                                {{ trans('global.app_select_all') }}
                            </button>
                            <button type="button" class="btn btn-primary btn-xs" id="deselectbtn-role">
                                {{ trans('global.app_deselect_all') }}
                            </button>
                            {!! Form::select('role[]', $roles, old('role') ? old('role') : $user->role->pluck('id')->toArray(), ['class' => 'form-control select2', 'multiple' => 'multiple', 'id' => 'selectall-role' , 'required' => '']) !!}
                            <p class="help-block"></p>
                            @if($errors->has('role'))
                                <p class="help-block">
                                    {{ $errors->first('role') }}
                                </p>
                            @endif
                        </div>
                    </div>

                </div>
            </div>

            {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
        </div>
    </div>

@stop

@section('javascript')
    @parent

    <script>
        $("#selectbtn-role").click(function () {
            $("#selectall-role > option").prop("selected", "selected");
            $("#selectall-role").trigger("change");
        });
        $("#deselectbtn-role").click(function () {
            $("#selectall-role > option").prop("selected", "");
            $("#selectall-role").trigger("change");
        });
    </script>
@stop

resources/views/admin/users/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-md-6  col-md-offset-3">
            @include('include.messages')

            <h3 class="page-title">@lang('global.users.title')</h3>
            {{--@can('user_create')--}}
                {{--<p>--}}
                    {{--<a href="{{ route('admin.users.create') }}" class="btn btn-primary">@lang('global.app_add_new')</a>--}}
                {{--</p>--}}
            {{--@endcan--}}


            <div class="panel panel-default">
                <div class="panel-heading">
                    @lang('global.app_list')
                </div>

                <div class="panel-body table-responsive">
                    <table class="table table-bordered table-striped {{ count($users) > 0 ? 'datatable' : '' }} @can('user_delete') dt-select @endcan">
                        <thead>
                        <tr>
                            @can('user_delete')
                                <th style="text-align:center;"><input type="checkbox" id="select-all"/></th>
                            @endcan

                            <th>@lang('global.users.fields.name')</th>
                            <th>@lang('global.users.fields.email')</th>
                            <th>@lang('global.users.fields.role')</th>
                            <th>&nbsp;</th>

                        </tr>
                        </thead>

                        <tbody>
                        @if (count($users) > 0)
                            @foreach ($users as $user)
                                <tr data-entry-id="{{ $user->id }}">
                                    @can('user_delete')
                                        <td></td>
                                    @endcan

                                    <td field-key='name'>{{ $user->name }}</td>
                                    <td field-key='email'>{{ $user->email }}</td>
                                    <td field-key='role'>
                                        @foreach ($user->role as $singleRole)
                                            <span class="label label-info label-many">{{ $singleRole->title }}</span>
                                        @endforeach
                                    </td>
                                    <td>
                                        @can('user_view')
                                            <a href="{{ route('admin.users.show',[$user->id]) }}"
                                               class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                        @endcan
                                        @can('user_edit')
                                            <a href="{{ route('admin.users.edit',[$user->id]) }}"
                                               class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                        @endcan
                                        @can('user_delete')
                                            {!! Form::open(array(
                                                                                    'style' => 'display: inline-block;',
                                                                                    'method' => 'DELETE',
                                                                                    'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                                                                    'route' => ['admin.users.destroy', $user->id])) !!}
                                            {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                            {!! Form::close() !!}
                                        @endcan
                                    </td>

                                </tr>
                            @endforeach
                        @else
                            <tr>
                                <td colspan="10">@lang('global.app_no_entries_in_table')</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('javascript')
    <script>
        @can('user_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.users.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-md-6  col-md-offset-3">
            @include('include.messages')

            <h3 class="page-title">@lang('global.users.title')</h3>

            <div class="panel panel-default">
                <div class="panel-heading">
                    @lang('global.app_view')
                </div>

                <div class="panel-body table-responsive">
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-bordered table-striped">
                                <tr>
                                    <th>@lang('global.users.fields.name')</th>
                                    <td field-key='name'>{{ $user->name }}</td>
                                </tr>
                                <tr>
                                    <th>@lang('global.users.fields.email')</th>
                                    <td field-key='email'>{{ $user->email }}</td>
                                </tr>
                                <tr>
                                    <th>@lang('global.users.fields.role')</th>
                                    <td field-key='role'>
                                        @foreach ($user->role as $singleRole)
                                            <span class="label label-info label-many">{{ $singleRole->title }}</span>
                                        @endforeach
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div><!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">

                        <li role="presentation" class="active"><a href="#ledger" aria-controls="ledger" role="tab"
                                                                  data-toggle="tab">Ledger</a></li>
                    </ul>

                    <!-- Tab panes -->
                    <div class="tab-content">

                        <div role="tabpanel" class="tab-pane active" id="ledger">
                            <table class="table table-bordered table-striped {{ count($ledgers) > 0 ? 'datatable' : '' }}">
                                <thead>
                                <tr>
                                    <th>@lang('global.ledger.fields.date-time')</th>
                                    <th>@lang('global.ledger.fields.amount')</th>
                                    <th>@lang('global.ledger.fields.type')</th>
                                    <th>@lang('global.ledger.fields.details')</th>
                                    <th>@lang('global.ledger.fields.created-by')</th>
                                    <th>@lang('global.ledger.fields.balance')</th>
                                    <th>&nbsp;</th>

                                </tr>
                                </thead>

                                <tbody>
                                @if (count($ledgers) > 0)
                                    @foreach ($ledgers as $ledger)
                                        <tr data-entry-id="{{ $ledger->id }}">
                                            <td field-key='date_time'>{{ $ledger->date_time }}</td>
                                            <td field-key='amount'>{{ $ledger->amount }}</td>
                                            <td field-key='type'>{{ $ledger->type }}</td>
                                            <td field-key='details'>{{ $ledger->details }}</td>
                                            <td field-key='created_by'>{{ $ledger->created_by->name ?? '' }}</td>
                                            <td field-key='balance'>{{ $ledger->balance }}</td>
                                            <td>
                                                @can('ledger_view')
                                                    <a href="{{ route('admin.ledgers.show',[$ledger->id]) }}"
                                                       class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                                @endcan
                                                @can('ledger_edit')
                                                    <a href="{{ route('admin.ledgers.edit',[$ledger->id]) }}"
                                                       class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                                @endcan
                                            </td>

                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="10">@lang('global.app_no_entries_in_table')</td>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <p>&nbsp;</p>

                    <a href="{{ route('admin.users.index') }}"
                       class="btn btn-default">@lang('global.app_back_to_list')</a>

                </div>
            </div>

        </div>
    </div>
@stop